# Generated by Django 4.0.7 on 2023-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i.pinimg.com/564x/12/90/f4/1290f474c64383be6663d8c2f4905cb2.jpg', max_length=500),
        ),
    ]
